### ISSUE TITLE
Add missing files: style.css and chatbot.js

### ISSUE THREAD

**Issue by 66666666666u6666** [66666666666u6666/ayaanlejipo.com#2]
The following two files are missing and need to be added to the project:

1. style.css
2. chatbot.js

Please provide the required content for these files or clarify if further specifications are needed.

**Comment by 66666666666u6666** [comment]
Waa kuwan labada fayl ee kuu dhiman:

---

*1. `style.css`*
```css
body {
  margin: 0;
  font-family: Arial, sans-serif;
  background-color: #000;
  color: #fff;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
}

#chatbox {
  width: 300px;
  height: 400px;
  background: #222;
  border-radius: 10px;
  display: flex;
  flex-direction: column;
  padding: 10px;
}

#chatlogs {
  flex: 1;
  overflow-y: auto;
  border: 1px solid #555;
  margin-bottom: 10px;
  padding: 5px;
}

#userInput {
  flex: none;
  padding: 8px;
  width: calc(100% - 70px);
  border: none;
  border-radius: 5px 0 0 5px;
  outline: none;
}

button {
  width: 60px;
  border: none;
  background: #4CAF50;
  color: white;
  border-radius: 0 5px 5px 0;
  cursor: pointer;
}
```

---

*2. `chatbot.js`*
```javascript
function sendMessage() {
  const input = document.getElementById('userInput');
  const chatlogs = document.getElementById('chatlogs');
  const userText = input.value.trim();
  if (!userText) return;

  const userMsg = document.createElement('div');
  userMsg.style.textAlign = 'right';
  userMsg.textContent = 'Adiga: ' + userText;
  chatlogs.appendChild(userMsg);

  input.value = '';

  const botMsg = document.createElement('div');
  botMsg.style.textAlign = 'left';
